node {

  // Commit 한 개발자 정보를 얻고자 하는 경우 아래 to 를 사용
  //def to = emailextrecipients([
  //        [$class: 'CulpritsRecipientProvider'],
  //        [$class: 'DevelopersRecipientProvider'],
  //        [$class: 'RequesterRecipientProvider']
  //])

  // job
  try {
    stage('build') {
      println('so far so good...')
    }
    stage('test') {
      println('A test has failed!')
      sh 'exit 1'
    }
  } catch(e) {
    // mark build as failed
    currentBuild.result = "FAILURE";
    // set variables
    def subject = "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} ${currentBuild.result}"
    def content = '${JELLY_SCRIPT,template="html"}'

    // send email
    if(to != null && !to.isEmpty()) {
       emailext(body: content, mimeType: 'text/html',
          replyTo: '$DEFAULT_REPLYTO',  // email configuration 에서 설정한 Replyto(CC)
          subject: subject,
          to: '$DEFAULT_RECIPIENTS', // email configuration 에서 설정한 Recipeents
          attachLog: true )
    }

    // mark current build as a failure and throw the error
    throw e;
  }
}
